$font = CaskaydiaCove Nerd Font Mono

general {
    hide_cursor = true
    ignore_empty_input = true
}

# uncomment to enable fingerprint authentication
auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250 # in milliseconds
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = $HOME/.cache/current_wallpaper/current.jpg
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 0
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_spacing = 0.3

    position = 0, 100
    halign = center
    valign = bottom
}

# Time hours
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")"
    color = rgba(255, 255, 255, 1)
    shadow_pass = 2
    shadow_size = 3
    shadow_color = rgb(0,0,0)
    shadow_boost = 1.2
    font_size = 150
    font_family = CaskaydiaCove Nerd Font Mono ExtraBold
    position = 0, -250
    halign = center
    valign = top
}

# Time minutes
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%M")"
    color = rgba(255, 255, 255, 1)
    font_size = 150
    font_family = CaskaydiaCove Nerd Font Mono ExtraBold
    position = 0, -420
    halign = center
    valign = top
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %b %A")"
    color = rgba(255, 255, 255, 1)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -130
    halign = center
    valign = center
}
